### ISSUE TITLE
With `JSON bool output without quotes` enabled shows "no tasks enabled or visible..."

### ISSUE THREAD

**Issue by tonhuisman** [chromoxdor/easyfetch#5]
On my units I mostly have the Tools/Advanced setting `JSON bool output without quotes:` checked, as formal JSON booleans are either `true` or `false`, and not string values...
Net result is that this check `sensor.TaskEnabled === "true"` isn't working.

For funnn I changed it into `(sensor.TaskEnabled === "true" || sensor.TaskEnabled === true)` (2x in the source) and it works as intended.

Not sure how all the minification and gzipping is to be done, so I'll leave fixing this to you @chromoxdor, or you could document that in a `CONTRIBUTING.md` or a short how-to in the `README.md` 😸.

**Comment by chromoxdor** [comment]
Hey @tonhuisman,

thanks for this... i never used `JSON bool output without quotes:`
I could not test the changes though, because i don´t have any hardware with me until next week..

> Not sure how all the minification and gzipping is to be done

Actually i just minify the edited files in the `/Test` folder and replace the content in the `fetch.html` file.
E.g. for JS i use [https://www.toptal.com/developers/javascript-minifier](url) and then copy and paste the content inside the `<script> `tags. For css is use a plugin in vs-code (but one could also use the toptal compressor) and then copy the content inside the <style> tags.
When the `fetch.html `is saved compress it to `fetch.html.gz` (i use keka for mac) and then i make a copy of `fetch.html.gz` and rename it to `index.htm.gz `.
